######### NORMAL OPERATION  ###########

### Login the default admin
POST http://localhost:3000/auths/login
Content-Type: application/json

{
    "username":"admin",
    "password":"admin"
}


### Create the manager user
POST http://localhost:3000/auths/register
Content-Type: application/json

{
    "username":"manager",
    "password":"manager"
}

### Create the dev user
POST http://localhost:3000/auths/register
Content-Type: application/json

{
    "username":"dev",
    "password":"dev"
}